name = "vs-twitter"
main = "src/index.ts"
compatibility_date = "2022-10-21"
node_compat = true

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false

[vars]
DISCORD_OWNER_ID = "195512978634833920"

# make sure to add these secrets to the environment:
# - DISCORD_APPLICATION_ID
# - DISCORD_PUBLIC_KEY
# - DISCORD_SECRET
# - TWITTER_API_KEY
# - TWITTER_API_SECRET
# - TWITTER_BEARER_TOKEN
